---
title: "Homework 2 - P8105"
author: "Sergio Ozoria Ramírez (smo2147)"
date: "2025-10-01"
output: github_document
---

# Problem 0.0

```{r setup, message =  FALSE}
library(tidyverse)
```

# Problem 1

#### Cleaning the `pols-month.csv` dataset 

```{r tidying pls dataset, message =  FALSE}
pls_month_df =
  read_csv("./Data/FiveThirtyEight/pols-month.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(mon, sep = "-", into = c("year", "month", "day")) |>
  mutate(across(year:day, as.integer),
         month = factor(month,
                        levels = 1:12,
                        labels = tolower(month.abb))) |> 
  mutate(president = case_when(
         prez_gop == 1 ~ "gop",
         prez_gop == 0 ~ "dem",
         TRUE ~ NA_character_ )) |> 
  relocate(year, month, president) |> 
  select(-day, -prez_gop, -prez_dem) |> 
  arrange(year, month)
```

#### Cleaning the `snp.csv` dataset 

```{r tidying snp dataset, message =  FALSE}
stock_market_df =
  read_csv("./Data/FiveThirtyEight/snp.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  separate(date, sep = "/", into = c("month", "day", "year")) |> 
  mutate(
    across(month:year, as.integer),
    year = ifelse(year 
                  <= 49, year + 2000, 
                  year + 1900),
    month = factor(month, 
                   levels = 1:12, 
                   labels = tolower(month.abb))) |> 
  relocate(year) |> 
  select(-day) |> 
  arrange(year, month)
```

#### Tidying the `umeployment` dataset

```{r tidying unemp dataset, message =  FALSE}
unemp_df =
  read_csv("./Data/FiveThirtyEight/unemployment.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemp_rate") |> 
  mutate(
    year = as.integer(year),
    month = factor(month,
                   labels = tolower(month.abb))) |> 
  arrange(year, month)
```

#### Merging `snp`, `pols` and `unemployment` datasets

```{r tidying merged dataset, message =  FALSE}
pls_snp_unemp_df =
  left_join(pls_month_df, stock_market_df, by = c("year", "month")) |>
  left_join(unemp_df, by = c("year", "month")) |> 
  arrange(year, month)
```

